name: tcss565
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
      - folium
      - geopandas
      - geopy
      - gmaps
      - hydra-core
      - kaggle
      - mapclassify
      - matplotlib
      - rich
      - tqdm
